apiVersion: v1
kind: Service
metadata:
  name: filter-service
  labels:
    app: filter-service
spec:
  type: ClusterIP
  selector:
    app: filter-service
  ports:
    - protocol: TCP
      port: 9006
      targetPort: 9006